//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosYEstados
    {
        public int idPedEstado { get; set; }
        public Nullable<int> nroPedido { get; set; }
        public Nullable<int> idEstadoPedido { get; set; }
        public Nullable<int> idEmpleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual EstadosPedidos EstadosPedidos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
