//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesisWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_Operaciones
    {
        public int idRolOperacion { get; set; }
        public Nullable<int> idRol { get; set; }
        public Nullable<int> idOperacion { get; set; }
    
        public virtual Operaciones Operaciones { get; set; }
        public virtual RolesUsuarios RolesUsuarios { get; set; }
    }
}
